Analytical measurement procedure
Biometric procedure
Test development Assessment procedure
Animal study
Cell study
Genetic engineering / Gene sequencing
Biochemistry
Material development
Genetic study
Clinical study (Phase 1)
Clinical study (Phase 2)
Clinical study (Phase 3)
Clinical study (Phase 4)
Therapy study (without intervention)
Prognostic study
Diagnostic study
Observational study with drugs
Secondary data analysis
Case series
Single case report
Interventional field study
Interventional group study
Prospective cohort study
Historical cohort study
Case control study
Cross-sectional study
Ecological study
Monitoring, Surveillance
Description with registry data